<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0</TargetFrameworks>

    <Version>3.2.0</Version>

    <Description>Microsoft.Extensions.DependencyInjection integration for WitRPC server, providing easy registration and lifecycle management of WitRPC server services.</Description>
    <PackageTags>OutWit;Communication;WitRPC;DependencyInjection;DI;Server</PackageTags>

    <RepositoryUrl>https://github.com/dmitrat/WitRPC/tree/main/Communication/OutWit.Communication.Server.DependencyInjection</RepositoryUrl>

  </PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0' or '$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutWit.Communication.Server\OutWit.Communication.Server.csproj" />
    <ProjectReference Include="..\OutWit.Communication.Server.Rest\OutWit.Communication.Server.Rest.csproj" />
  </ItemGroup>

</Project>
