<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="OutWit.Common.Logging" />
		<PackageReference Include="OutWit.Common.MVVM" />
		<PackageReference Include="protobuf-net.Grpc.ClientFactory" />
		<PackageReference Include="System.ServiceModel.Http" />
		<PackageReference Include="System.ServiceModel.NetNamedPipe" />
		<PackageReference Include="System.ServiceModel.NetTcp" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Client.DynamicProxy\OutWit.Communication.Client.DynamicProxy.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Serializers.MessagePack\OutWit.Communication.Serializers.MessagePack.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Serializers.ProtoBuf\OutWit.Communication.Serializers.ProtoBuf.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Client.MMF\OutWit.Communication.Client.MMF.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Client.Pipes\OutWit.Communication.Client.Pipes.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Client.Tcp\OutWit.Communication.Client.Tcp.csproj" />
		<ProjectReference Include="..\..\..\Communication\OutWit.Communication.Client.WebSocket\OutWit.Communication.Client.WebSocket.csproj" />
		<ProjectReference Include="..\..\OutWit.Examples.Contracts\OutWit.Examples.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="GRPCSettingsTab.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="SignalRSettingsTab.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="WCFSettingsTab.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="WitRPCSettingsTab.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>

</Project>
