using System;
using System.Security.Cryptography;
using System.Text.Json.Serialization;

namespace OutWit.Common.Json
{
    [JsonSerializable(typeof(bool))]
    [JsonSerializable(typeof(byte))]
    [JsonSerializable(typeof(sbyte))]
    [JsonSerializable(typeof(short))]
    [JsonSerializable(typeof(ushort))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(uint))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(ulong))]
    [JsonSerializable(typeof(float))]
    [JsonSerializable(typeof(double))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(char))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTimeOffset))]
    [JsonSerializable(typeof(Guid))]
    [JsonSerializable(typeof(Uri))]
    [JsonSerializable(typeof(TimeSpan))]
    [JsonSerializable(typeof(Type))]
    [JsonSerializable(typeof(RSAParameters))]

    [JsonSerializable(typeof(bool[]))]
    [JsonSerializable(typeof(byte[]))]
    [JsonSerializable(typeof(sbyte[]))]
    [JsonSerializable(typeof(short[]))]
    [JsonSerializable(typeof(ushort[]))]
    [JsonSerializable(typeof(int[]))]
    [JsonSerializable(typeof(uint[]))]
    [JsonSerializable(typeof(long[]))]
    [JsonSerializable(typeof(ulong[]))]
    [JsonSerializable(typeof(float[]))]
    [JsonSerializable(typeof(double[]))]
    [JsonSerializable(typeof(decimal[]))]
    [JsonSerializable(typeof(char[]))]
    [JsonSerializable(typeof(string[]))]
    [JsonSerializable(typeof(DateTime[]))]
    [JsonSerializable(typeof(DateTimeOffset[]))]
    [JsonSerializable(typeof(Guid[]))]
    [JsonSerializable(typeof(Uri[]))]
    [JsonSerializable(typeof(TimeSpan[]))]
    [JsonSerializable(typeof(Type[]))]
    [JsonSerializable(typeof(RSAParameters[]))]

    [JsonSerializable(typeof(List<bool>))]
    [JsonSerializable(typeof(List<byte>))]
    [JsonSerializable(typeof(List<sbyte>))]
    [JsonSerializable(typeof(List<short>))]
    [JsonSerializable(typeof(List<ushort>))]
    [JsonSerializable(typeof(List<int>))]
    [JsonSerializable(typeof(List<uint>))]
    [JsonSerializable(typeof(List<long>))]
    [JsonSerializable(typeof(List<ulong>))]
    [JsonSerializable(typeof(List<float>))]
    [JsonSerializable(typeof(List<double>))]
    [JsonSerializable(typeof(List<decimal>))]
    [JsonSerializable(typeof(List<char>))]
    [JsonSerializable(typeof(List<string>))]
    [JsonSerializable(typeof(List<DateTime>))]
    [JsonSerializable(typeof(List<DateTimeOffset>))]
    [JsonSerializable(typeof(List<Guid>))]
    [JsonSerializable(typeof(List<Uri>))]
    [JsonSerializable(typeof(List<TimeSpan>))]
    [JsonSerializable(typeof(List<Type>))]
    [JsonSerializable(typeof(List<RSAParameters>))]

    internal partial class JsonContextDefault : JsonSerializerContext
    {
    }
}
